### ISSUE TITLE
ERP plot - stimulus vs response, switching causes error

### ISSUE THREAD

**Issue by jrliu95** [ben-dichter-consulting/ecogVIS#27]
On the ERP plot, I see there's buttons for stimulus and response. What exactly do these correspond to? For CVs, I would assume that stimulus corresponds to the listening portion (from the speaker channel) and that response corresponds to the speaking portion (from the mic channel).

When I tried to click between "stimulus" and "response" I often got this error in my ipython session. I don't think it successfully changes the plot either, only when switching between onset and offset does the plot change.

![Screen Shot 2019-07-25 at 10 29 05 AM](https://user-images.githubusercontent.com/17503400/61895262-1ecd3280-aec7-11e9-9fde-63dd274f6fc1.png)

If I'm on "onset" and trying to switch between stimulus and response, the shapes it can't broadcast are (0) to (800). Once I switch to "offset" the shapes it can't broadcast (as in the above image) are (420) to (800). It's always at line 1731 in `subDialogs`.

**Comment by luiztauffer** [comment]
> On the ERP plot, I see there's buttons for stimulus and response. What exactly do these correspond to? For CVs, I would assume that stimulus corresponds to the listening portion (from the speaker channel) and that response corresponds to the speaking portion (from the mic channel).

That's right, that's what they correspond to.

> When I tried to click between "stimulus" and "response" I often got this error in my ipython session. I don't think it successfully changes the plot either, only when switching between onset and offset does the plot change.

Is this error causing the program to crash? Can I have access to the file you're using to test it? In my files this is working as expected.

> ![Screen Shot 2019-07-25 at 10 29 05 AM](https://user-images.githubusercontent.com/17503400/61895262-1ecd3280-aec7-11e9-9fde-63dd274f6fc1.png)
> 
> If I'm on "onset" and trying to switch between stimulus and response, the shapes it can't broadcast are (0) to (800). Once I switch to "offset" the shapes it can't broadcast (as in the above image) are (420) to (800). It's always at line 1731 in `subDialogs`.

**Comment by luiztauffer** [comment]
Latest update should resolve this, please let me know if it solved for you!

**Comment by jrliu95** [comment]
I think the main issue was stemming from the detected times. Once I messed around with it and got it to be more accurate, it seemed fine!
