### ISSUE TITLE
Way to make the cp_objs dictionary customizable?

### ISSUE THREAD

**Issue by jrliu95** [ben-dichter-consulting/ecogVIS#36]
In `ecogvis.signal_processing.processing_data.make_new_nwb`, the objectives dictionary is predefined. I don't have any `epochs` information in the files I've been making, so when it tries to copy it over, it obviously gets an error. Is there some way to make this customizable in the kwargs of the function? I call this function directly in a script to batch preprocess files without the GUI. Let me know if there's some other way I can get around this.

https://github.com/ben-dichter-consulting/ecogVIS/blob/297f199f1259c2e62784a13db1aeba534849a9cc/ecogvis/signal_processing/processing_data.py#L56

This is a short excerpt from my code to show you how I'm calling the functions.

```
if export_high_gamma:
    # If exporting high gamma to a new file, create that new file.
    new_file = os.path.join(general_path, '{}_B{}_hg.nwb'.format(subject, block))
    make_new_nwb(old_file=block_path, new_file=new_file)
    print('Made new NWB file for high gamma data.', flush=True)
else:
    # Otherwise, provide an empty string to save the high gamma to
    # the existing file.
    new_file = ''

if not file_hg:
    # Compute high gamma data. Save to separate file if specified.
    high_gamma_estimation(block_path,
                                  bands_vals=config['hg_bands_vals'],
                                  new_file=new_file)
```

**Comment by luiztauffer** [comment]
@jrliu95  cp_objs has now a default value of None, which is updated if you dont provide your own dictionary. Hope that helps!
This nwb_copy function is a partial solution, while the pynwb team dont sort out a direct way of making copies without links. It's been working for the files I had and classes we've been using, but its prone to errors just like the one you described. You're welcome to PR future improvements whenever you face similar problems!

**Comment by jrliu95** [comment]
Thanks, and will do!

One other question on this, it seems like the value of the `cp_objs` doesn't matter, it only checks whether that key is present:

https://github.com/ben-dichter-consulting/ecogVIS/blob/9ce2a4bc7be14bedfb48f7b0231773da7dd8fa32/ecogvis/functions/nwb_copy_file.py#L52

So, if I set `epochs` to `False` it will still try to copy those over. Excluding it from the dictionary solves this, but then there's not really a point to have a dictionary.

**Comment by luiztauffer** [comment]
The point is for fields such as `acquisition` or `processing`, where you might have several children. In those cases, the dict value is a list of strings containing the names of children that should be copied. If you're copying all that's contained in a given group, you just pass the value True

**Comment by luiztauffer** [comment]
But you're right, it is not using the True as a test condition, it is using just as a placeholder

**Comment by jrliu95** [comment]
Ooh, I see! Thanks for the clarification!
