### ISSUE TITLE
PERIODOGRAM - grid plots

### ISSUE THREAD

**Issue by luiztauffer** [ben-dichter-consulting/ecogVIS#7]

**Comment by luiztauffer** [comment]
@jrliu95  @bendichter
It has been difficult to achieve 3D plots with quality/performance similar to the ones you shared (produced matlab). A solution so far was to produce 16x16 grids similar to the ERP ones. 
On the positive side, it preserves the anatomical sense and facilitates individual inspection (you can double-click and inspect individual Periodogram in detail).
On the negative side, it is not as visually summarizing as the 3D plot. 
Let me know what you think of that and what you think should be made differently.

**Comment by jrliu95** [comment]
I get this error when trying to calculate the spectrum data for the periodogram.

```KeyError                                  Traceback (most recent call last)
~/ChangLab/projects/ecogVIS/ecogvis/functions/subDialogs.py in run(self)
    200     def run(self):
    201         psd_estimate(src_file=self.src_file,
--> 202                      type=self.type)
    203 
    204 

~/ChangLab/projects/ecogVIS/ecogvis/signal_processing/periodogram.py in psd_estimate(src_file, type)
     22         #Source ElectricalSeries
     23         if type=='raw':
---> 24             data_obj = nwb.acquisition['ElectricalSeries']
     25         elif type=='preprocessed':
     26             data_obj = nwb.processing['ecephys'].data_interfaces['LFP'].electrical_series['preprocessed']

/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/pynwb/core.py in __getitem__(self, args)
     55                 return ret if len(ret) else None
     56             key = val
---> 57         return super(LabelledDict, self).__getitem__(key)
     58 
     59 

KeyError: 'ElectricalSeries'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/ChangLab/projects/ecogVIS/ecogvis/ecogvis.py in PeriodogramSelect(self)
    724             try:  #tries to read fft and welch spectral data
--> 725                 psd_fft = self.model.nwb.modules['ecephys'].data_interfaces['Spectrum_fft_raw']
    726                 psd_welch = self.model.nwb.modules['ecephys'].data_interfaces['Spectrum_welch_raw']

/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/pynwb/core.py in __getitem__(self, args)
     56             key = val
---> 57         return super(LabelledDict, self).__getitem__(key)
     58 

KeyError: 'Spectrum_fft_raw'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/ChangLab/projects/ecogVIS/ecogvis/ecogvis.py in PeriodogramSelect(self)
    731                     self.model.refresh_file()  # re-opens the file, now with new data
    732                     self.combo3.setCurrentIndex(self.combo3.findText('raw'))
--> 733                     psd_fft = self.model.nwb.modules['ecephys'].data_interfaces['Spectrum_fft_raw']
    734                     psd_welch = self.model.nwb.modules['ecephys'].data_interfaces['Spectrum_welch_raw']
    735                     PeriodogramGridDialog(self)

/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/pynwb/core.py in __getitem__(self, args)
     55                 return ret if len(ret) else None
     56             key = val
---> 57         return super(LabelledDict, self).__getitem__(key)
     58 
     59 

KeyError: 'Spectrum_fft_raw'
```

The raw data is indeed an ElectricalSeries with the name `ECoG`, which works with the other preprocessing steps.

**Comment by luiztauffer** [comment]
The convention is (this is recent) to have the name of the principal ElectricalSeries data container as 'ElectricalSeries'.
Is it an easy thing to change in your files? If not, I can add a possibility to load from the old 'ECoG' as well!

**Comment by jrliu95** [comment]
That's a super easy change on my part! Do the initial preprocessing steps just grab from the only ElectricalSeries in the file?

**Comment by luiztauffer** [comment]
Yes, they work because I only test if the data contained there is of 'ElectricalSeries' type or not, regardless of the name. It felt important to check strictly for the main source of voltage data only when running the PSD estimation. This is an easy thing to change in the future, if needed!

**Comment by jrliu95** [comment]
Gotcha, works now! This brings up another question of how you draw the grids (for both the periodogram and the ERPs). Not every subject has a 16 x 16 grid, sometimes there are 2 or 3 separate 128 channel grids. I believe I have the electrode tables set up to put separate grids (and other strip or depth electrodes) as separate devices. For example, if there are 2 128 channel grids, one strip, and 4 depths, there would be a total of 7 devices.

In the GUI, we only need to plot the larger grids, not the strips or depths. Is there an easy way to create separate grids? I'm not sure how the Matlab GUI does this actually but I think it does plot separate grids if there is more than 1.

**Comment by luiztauffer** [comment]
It shouldn't be difficult, but something I'd have to look more carefully into.
Is there any such file, with 2x128 grid channels, that you could share with me?

**Comment by jrliu95** [comment]
Okay, I will also look into the Matlab code to see if I can find how it handles this.

And yes, I'll prep a file and share via email! Thanks

**Comment by luiztauffer** [comment]
@jrliu95  what are the lengths of each dimension in non-256 grids? Do you have standard nRows x nCols for each electrode group?

**Comment by jrliu95** [comment]
They will always be 16 x 8. The custom for electrode numbering order is that it goes along the size 16 dimension first, typically from the bottom right corner, I believe. Meaning that if you had a 16 x 8 matrix, matrix[15, 7]=1, matrix[14, 7]=2 and so on. I hope that's not confusing!

**Comment by luiztauffer** [comment]
ok, a set of functions for choosing the specific grid and rotating/flipping it are in place for ERP.
Let me know if you think this works well for your visualization purposes and then I implement the same thing for the Periodograms!

**Comment by jrliu95** [comment]
This is great! I really like the drop-down menu. It seems like I can't choose the button to rotate the grid though? To make it 16x8 instead of 8x16

<img width="1287" alt="Screen Shot 2019-07-29 at 2 27 22 PM" src="https://user-images.githubusercontent.com/17503400/62083985-ff0e7500-b20c-11e9-8bd5-f8a80929f683.png">

**Comment by luiztauffer** [comment]
Yes, the upper grid operations will only work with square matrices (16x16). All other changes in order can be accomplished with the 'rearrange' operations below.
Is it important to display it vertically?

**Comment by jrliu95** [comment]
Would it be difficult to do it that way? I think this is important to have, for example in the above plot, the way it's plotted right now, anterior-posterior is north-south, which isn't intuitive. You could even just plot it 16x16 but just fill the other half with empty plots if there's no other easy way? That way it'd still be able to be rotated?
